# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'card-tutorial' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
pod 'Cards'
    pod 'SnapKit', '~> 5.0.0'
  # Pods for card-tutorial

end
